package amdgpu

// CHIP_CLASS represents the AMD GPU chip class/generation.
// Used to select appropriate performance counter layouts and feature sets.
type CHIP_CLASS uint32

const (
	CLASS_UNKNOWN CHIP_CLASS = iota
	R300
	R400
	R500
	R600
	R700
	EVERGREEN
	CAYMAN
	GFX6
	GFX7
	GFX8
	GFX9
	GFX10
	GFX10_3
	GFX11
	GFX11_5
	GFX12
)

// ASIC_NAME represents the specific AMD GPU ASIC name.
type ASIC_NAME uint32

const (
	ASIC_UNKNOWN ASIC_NAME = iota
	// GFX6
	TAHITI
	PISENES
	CAICOS
	CYPRESS
	JUNIPER
	CEDAR
	REDWOOD
	CAYMAN_ASIC
	BARTS
	TURKS
	VERDE
	OLDFI
	PALM
	// GFX7
	SHARKISLAND
	STONEY
	OCEANIA
	HAWAII
	KABINI
	MULLINS
	KAVERI
	RICHARDVILLE
	Iceland
	TEMPLE
	// GFX8
	TONGA
	FIREPRO
	VIC
	FLAME
	// GFX9
	VEGAN10
	VEGAN11
	POLARIS10
	POLARIS11
	POLARIS12
	ELLCIN
	FIJI
	STARFIS
	// GFX10
	NAV10
	NAV11
	NAV12
	// GFX10_3
	NAV21
	NAV22
	NAV23
	// GFX11
	NAV31
	NAV32
	// GFX12
	GRANITE_RIDGE
)

// HW_IP_TYPE represents hardware IP block types.
type HW_IP_TYPE uint32

const (
	HW_IP_TYPE_GFX HW_IP_TYPE = iota
	HW_IP_TYPE_COMPUTE
	HW_IP_TYPE_DMA
	HW_IP_TYPE_UVD
	HW_IP_TYPE_VCE
	HW_IP_TYPE_UVD_ENC
	HW_IP_TYPE_VCN_DEC
	HW_IP_TYPE_VCN_ENC
	HW_IP_TYPE_VCN_JPEG
	HW_IP_TYPE_VPE
)

// SENSOR_TYPE represents sensor query types.
type SENSOR_TYPE uint32

const (
	SENSOR_TYPE_GFX_SCLK SENSOR_TYPE = iota + 1
	SENSOR_TYPE_GFX_MCLK
	SENSOR_TYPE_THM_TEMPERATURE
	SENSOR_TYPE_EDGE_TEMPERATURE
	SENSOR_TYPE_JUNCTION_TEMPERATURE
	SENSOR_TYPE_MEM_TEMPERATURE
	SENSOR_TYPE_VDDGFX
	SENSOR_TYPE_VDDNB
	SENSOR_TYPE_FAN_SPEED
	SENSOR_TYPE_FAN_RPM
)

// AMDGPU_INFO_FW represents firmware query types (values from amdgpu_drm.h).
type AMDGPU_INFO_FW uint32

const (
	AMDGPU_INFO_FW_VCE     AMDGPU_INFO_FW = 0x01
	AMDGPU_INFO_FW_UVD     AMDGPU_INFO_FW = 0x02
	AMDGPU_INFO_FW_GMC     AMDGPU_INFO_FW = 0x03
	AMDGPU_INFO_FW_GFX_ME  AMDGPU_INFO_FW = 0x04
	AMDGPU_INFO_FW_GFX_PFP AMDGPU_INFO_FW = 0x05
	AMDGPU_INFO_FW_GFX_CE  AMDGPU_INFO_FW = 0x06
	AMDGPU_INFO_FW_GFX_RLC AMDGPU_INFO_FW = 0x07
	AMDGPU_INFO_FW_GFX_MEC AMDGPU_INFO_FW = 0x08
	AMDGPU_INFO_FW_SMC     AMDGPU_INFO_FW = 0x0a
	AMDGPU_INFO_FW_SDMA    AMDGPU_INFO_FW = 0x0b
	AMDGPU_INFO_FW_SOS     AMDGPU_INFO_FW = 0x0c
	AMDGPU_INFO_FW_ASD     AMDGPU_INFO_FW = 0x0d
	AMDGPU_INFO_FW_VCN     AMDGPU_INFO_FW = 0x0e
	AMDGPU_INFO_FW_DMCU    AMDGPU_INFO_FW = 0x12
	AMDGPU_INFO_FW_TA      AMDGPU_INFO_FW = 0x13
	AMDGPU_INFO_FW_DMCUB   AMDGPU_INFO_FW = 0x14
	AMDGPU_INFO_FW_TOC     AMDGPU_INFO_FW = 0x15
	AMDGPU_INFO_FW_CAP     AMDGPU_INFO_FW = 0x16
	AMDGPU_INFO_FW_GFX_RLCP AMDGPU_INFO_FW = 0x17
	AMDGPU_INFO_FW_GFX_RLCV AMDGPU_INFO_FW = 0x18
	AMDGPU_INFO_FW_MES_KIQ AMDGPU_INFO_FW = 0x19
	AMDGPU_INFO_FW_MES     AMDGPU_INFO_FW = 0x1a
	AMDGPU_INFO_FW_IMU     AMDGPU_INFO_FW = 0x1b
	AMDGPU_INFO_FW_VPE     AMDGPU_INFO_FW = 0x1c
)

var fwTypeNames = map[AMDGPU_INFO_FW]string{
	AMDGPU_INFO_FW_VCE:      "VCE",
	AMDGPU_INFO_FW_UVD:      "UVD",
	AMDGPU_INFO_FW_GMC:      "GMC",
	AMDGPU_INFO_FW_GFX_ME:   "GFX_ME",
	AMDGPU_INFO_FW_GFX_PFP:  "GFX_PFP",
	AMDGPU_INFO_FW_GFX_CE:   "GFX_CE",
	AMDGPU_INFO_FW_GFX_RLC:  "GFX_RLC",
	AMDGPU_INFO_FW_GFX_MEC:  "GFX_MEC",
	AMDGPU_INFO_FW_SMC:      "SMC",
	AMDGPU_INFO_FW_SDMA:     "SDMA",
	AMDGPU_INFO_FW_SOS:      "SOS",
	AMDGPU_INFO_FW_ASD:      "ASD",
	AMDGPU_INFO_FW_VCN:      "VCN",
	AMDGPU_INFO_FW_DMCU:     "DMCU",
	AMDGPU_INFO_FW_TA:       "TA",
	AMDGPU_INFO_FW_DMCUB:    "DMCUB",
	AMDGPU_INFO_FW_TOC:      "TOC",
	AMDGPU_INFO_FW_CAP:      "CAP",
	AMDGPU_INFO_FW_GFX_RLCP: "GFX_RLCP",
	AMDGPU_INFO_FW_GFX_RLCV: "GFX_RLCV",
	AMDGPU_INFO_FW_MES_KIQ:  "MES_KIQ",
	AMDGPU_INFO_FW_MES:      "MES",
	AMDGPU_INFO_FW_IMU:      "IMU",
	AMDGPU_INFO_FW_VPE:      "VPE",
}

// FWTypeName returns the display name for a firmware type (e.g. "GFX_ME").
func FWTypeName(fw AMDGPU_INFO_FW) string {
	if n, ok := fwTypeNames[fw]; ok {
		return n
	}
	return "UNKNOWN"
}

// hwIPTypeNames maps HW_IP_TYPE to the JSON display string used by amdgpu_top.
var hwIPTypeNames = map[HW_IP_TYPE]string{
	HW_IP_TYPE_GFX:      "GFX",
	HW_IP_TYPE_COMPUTE:  "COMPUTE",
	HW_IP_TYPE_DMA:      "DMA",
	HW_IP_TYPE_UVD:      "UVD",
	HW_IP_TYPE_VCE:      "VCE",
	HW_IP_TYPE_UVD_ENC:  "UVD_ENC",
	HW_IP_TYPE_VCN_DEC:  "VCN_DEC",
	HW_IP_TYPE_VCN_ENC:  "VCN_ENC",
	HW_IP_TYPE_VCN_JPEG: "VCN_JPEG",
	HW_IP_TYPE_VPE:      "VPE",
}

// HWIPTypeName returns the display name for a hardware IP type.
func HWIPTypeName(t HW_IP_TYPE) string {
	if n, ok := hwIPTypeNames[t]; ok {
		return n
	}
	return "UNKNOWN"
}
